"use client";
import {useMemo,useState} from "react";
const fields=[["rent", "שכר דירה חודשי", "6500", "₪"], ["tax", "ארנונה לחודש", "550", "₪"], ["hoa", "ועד בית", "250", "₪"], ["utilities", "חשמל ומים", "450", "₪"], ["internet", "אינטרנט וטלוויזיה", "180", "₪"], ["parking", "חניה / תחבורה", "0", "₪"]];
const initial=Object.fromEntries(fields.map(([key,,value])=>[key,Number(value)]));
const format=(n)=>new Intl.NumberFormat("he-IL",{maximumFractionDigits:0}).format(n);
export default function Home(){
 const [values,setValues]=useState(initial);
 const data=useMemo(()=>{ const total = values.rent + values.tax + values.hoa + values.utilities + values.internet + values.parking; return { total, primary: 'עלות חודשית אמיתית', secondary: `₪${format(total * 12)} בשנה`, rows: [['שכר דירה', values.rent], ['חשבונות ומסים', total-values.rent], ['עלות שנתית', total*12]] }; },[values]);
 return <main className="shell rent"><nav className="nav"><div className="brand">שכירות אמיתית<span className="dot">.</span></div><a href="#calculator">למחשבון ↓</a></nav><section className="hero"><div><div className="eyebrow">RENT SMARTER · ישראל</div><h1>הבית הבא שלך.
בלי הפתעות.</h1><p className="lead">מחשבון מגורים שעושה סדר בשכר הדירה, ארנונה, ועד בית והחשבונות — לפני שחותמים.</p></div><div className="heroArt" style={{'--hero':`url("https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=85")`}}><div className="floatTag"><span>תכנון חכם</span><b>מספרים שאפשר לסמוך עליהם</b></div></div></section><section id="calculator" className="calculator"><div className="panel"><h2>בואו נחשב</h2><p>שנו את המספרים — התוצאה מתעדכנת מיד.</p><div className="fields">{fields.map(([key,label,,unit])=><label key={key}>{label}<input aria-label={label} type="number" min="0" step="any" value={values[key]} onChange={e=>setValues(v=>({...v,[key]:Number(e.target.value)||0}))}/><small>{unit}</small></label>)}</div></div><aside className="result"><div><div className="resultLabel">{data.primary}</div><div className="total">₪{format(data.total)}</div><div className="secondary">{data.secondary}</div></div><div className="rows">{data.rows.map(([label,value])=><div className="row" key={label}><span>{label}</span><b>₪{format(value)}</b></div>)}</div></aside></section><section className="benefits"><div className="benefit"><i></i>משווים דירות לפי עלות אמיתית</div><div className="benefit"><i></i>מבינים את ההוצאה השנתית</div><div className="benefit"><i></i>חוסכים ויכוחים עם שותפים</div></section><footer className="footer">שכירות אמיתית · תכנון פשוט. החלטות טובות יותר.</footer></main>}
